# Generated by Django 3.0.3 on 2020-10-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_one', '0002_add_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='site',
            field=models.CharField(choices=[('beh', 'Behance'), ('blo', 'Blogger'), ('dri', 'Dribbble'), ('fac', 'Facebook'), ('fli', 'Flickr'), ('git', 'GitHub'), ('goo', 'Google'), ('ins', 'Instagram'), ('lin', 'LinkedIn'), ('med', 'Medium'), ('pin', 'Pinterest'), ('red', 'Reddit'), ('sky', 'Skype'), ('sna', 'Snapchat'), ('tum', 'Tumblr'), ('twi', 'Twitter'), ('you', 'YouTube'), ('oth', 'Other website')], max_length=7),
        ),
    ]
